[global]
showWarningOnDirectExecution = true

[logger]
level = "debug"

[runner]
magicEnabled = true

[server]
headless = true
port = 8501           # Recommended for Windows
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false  # Only if you need CORS disabled

[browser]
gatherUsageStats = true
